=== eqeuscom/RICSamples/RICAPIClientVFP/invoices.xsd
<?xml version="1.0" encoding="windows-1252" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:x-xfrx:schemas:dokument:1.0"  xmlns="urn:x-xfrx:schemas:dokument:1.0" elementFormDefault="qualified">

 <xs:complexType name="picture">
  <xs:attribute name="name" type="xs:string" use="required" />
  <xs:attribute name="left" type="xs:float" use="required" />
  <xs:attribute name="top" type="xs:float" use="required" />
  <xs:attribute name="width" type="xs:float" use="required" />
  <xs:attribute name="height" type="xs:float" use="required" />
  <xs:attribute name="borderwidth" type="xs:int" use="required" />
  <xs:attribute name="borderstyle" type="xs:int" use="required" />
  <xs:attribute name="bordercolor" type="xs:int" use="required" />
  <xs:attribute name="backcolor" type="xs:int" use="required" />
  <xs:attribute name="offset" type="xs:int" use="required" />
  <xs:attribute name="src" type="xs:string" use="required" />
  <xs:attribute name="data" type="xs:base64Binary" use="required" />
  <xs:attribute name="rctype" type="xs:string" use="required" />
 </xs:complexType>

 <xs:complexType name="line">
  <xs:attribute name="name" type="xs:string" use="required" />
  <xs:attribute name="left" type="xs:float" use="required" />
  <xs:attribute name="top" type="xs:float" use="required" />
  <xs:attribute name="width" type="xs:float" use="required" />
  <xs:attribute name="height" type="xs:float" use="required" />
  <xs:attribute name="borderwidth" type="xs:int" use="required" />
  <xs:attribute name="borderstyle" type="xs:int" use="required" />
  <xs:attribute name="bordercolor" type="xs:int" use="required" />
  <xs:attribute name="rctype" type="xs:string" use="required" />
 </xs:complexType>

 <xs:complexType name="rectangle">
  <xs:attribute name="name" type="xs:string" use="required" />
  <xs:attribute name="left" type="xs:float" use="required" />
  <xs:attribute name="top" type="xs:float" use="required" />
  <xs:attribute name="width" type="xs:float" use="required" />
  <xs:attribute name="height" type="xs:float" use="required" />
  <xs:attribute name="borderwidth" type="xs:int" use="required" />
  <xs:attribute name="borderstyle" type="xs:int" use="required" />
  <xs:attribute name="bordercolor" type="xs:int" use="required" />
  <xs:attribute name="backcolor" type="xs:int" use="required" />
  <xs:attribute name="fillstyle" type="xs:int" use="required" />
  <xs:attribute name="backstyle" type="xs:int" use="required" />
  <xs:attribute name="offset" type="xs:int" use="required" />
  <xs:attribute name="rctype" type="xs:string" use="required" />
 </xs:complexType>

 <xs:complexType name="textbox">
  <xs:attribute name="name" type="xs:string" use="required" />
  <xs:attribute name="left" type="xs:float" use="required" />
  <xs:attribute name="top" type="xs:float" use="required" />
  <xs:attribute name="width" type="xs:float" use="required" />
  <xs:attribute name="height" type="xs:float" use="required" />
  <xs:attribute name="forecolor" type="xs:int" use="required" />
  <xs:attribute name="backcolor" type="xs:int" use="required" />
  <xs:attribute name="backstyle" type="xs:int" use="required" />
  <xs:attribute name="fontname" type="xs:string" use="required" />
  <xs:attribute name="fontsize" type="xs:int" use="required" />
  <xs:attribute name="fontstyle" type="xs:string" use="required" />
  <xs:attribute name="align" type="xs:string" use="required" />
  <xs:attribute name="rctype" type="xs:string" use="required" />
  <xs:attribute name="uniqueid" type="xs:string" use="required" />
  <xs:attribute name="linkname" type="xs:string" use="required" />
  <xs:attribute name="linkref" type="xs:string" use="required" />
  <xs:attribute name="outline" type="xs:string" use="required" />
  <xs:attribute name="outlinestyle" type="xs:int" use="required" />
  <xs:attribute name="tooltip" type="xs:string" use="required" />
 </xs:complexType>

 <xs:complexType name="section">
  <xs:sequence>
   <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element name="picture" type="picture" />
    <xs:element name="line" type="line" />
    <xs:element name="rectangle" type="rectangle" />
    <xs:element name="textbox" type="textbox" />
   </xs:choice>
  </xs:sequence>
  <xs:attribute name="type" type="xs:int" use="required" />
  <xs:attribute name="height" type="xs:float" use="required" />
  <xs:attribute name="top" type="xs:float" use="required" />
  <xs:attribute name="rctype" type="xs:string" use="required" />
 </xs:complexType>

 <xs:complexType name="page">
  <xs:sequence>
   <xs:element name="section" type="section" minOccurs="0" maxOccurs="unbounded" />
  </xs:sequence>
  <xs:attribute name="order" type="xs:int" use="required" />
  <xs:attribute name="page" type="xs:int" use="required" />
  <xs:attribute name="width" type="xs:float" use="required" />
  <xs:attribute name="height" type="xs:float" use="required" />
  <xs:attribute name="rctype" type="xs:string" use="required" />
 </xs:complexType>

 <xs:complexType name="report">
  <xs:sequence>
   <xs:element name="page" type="page" minOccurs="1" maxOccurs="unbounded" />
  </xs:sequence>
  <xs:attribute name="id" type="xs:int" use="required" />
  <xs:attribute name="text" type="xs:string" use="required" />
  <xs:attribute name="pages" type="xs:int" use="required" />
  <xs:attribute name="TP" type="xs:float" use="required" />
  <xs:attribute name="BP" type="xs:float" use="required" />
  <xs:attribute name="LP" type="xs:float" use="required" />
  <xs:attribute name="RP" type="xs:float" use="required" />
  <xs:attribute name="TM" type="xs:float" use="required" />
  <xs:attribute name="TS" type="xs:float" use="required" />
  <xs:attribute name="LM" type="xs:float" use="required" />
  <xs:attribute name="RM" type="xs:float" use="required" />
  <xs:attribute name="BM" type="xs:float" use="required" />
  <xs:attribute name="UM" type="xs:float" use="required" />
  <xs:attribute name="rctype" type="xs:string" use="required" />
 </xs:complexType>

 <xs:element name="reports">
  <xs:complexType>
   <xs:sequence>
    <xs:element name="report" type="report" minOccurs="1" maxOccurs="unbounded" />
   </xs:sequence>
   <xs:attribute name="version" type="xs:string" use="required" />
  </xs:complexType>
 </xs:element>
</xs:schema>

=== eqeuscom/RICSamples/RICAPIClientVFP/invoices.xml
<?xml version="1.0" encoding="windows-1252" standalone="yes"?>
<xfrx:reports xmlns:xfrx="urn:x-xfrx:schemas:dokument:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:x-xfrx:schemas:dokument:1.0 invoices.xsd" version="0.1">
 <xfrx:report id="1" text="for clause: " pages="1" TP="0.000" BP="2000.000" LP="2100.000" RP="2100.000" TM="4000.000" TS="0.000" LM="2100.000" RM="2100.000" BM="4000.000" UM="0.000" rctype="J">
  <xfrx:page order="1" page="1" width="82677.00000" height="116929.0000" rctype="P">
   <xfrx:section type="4" height="1.000000" top="0.000000" rctype="S">
    <xfrx:picture name="px1" left="24729.16700" top="14927.08300" width="31979.16700" height="9166.667000" borderwidth="0" borderstyle="0" bordercolor="0" backcolor="0" offset="0" src="C:\USERS\MARTIN~1\APPDATA\LOCAL\TEMP\XK19LZA4\pic7.jpg" data="/9j/4AAQSkZJRgABAAEAYABgAAD//gAcQ3JlYXRlZCBieSBBY2N1U29mdCBDb3JwLgD/wAAR
CABYATMDASEAAhEBAxEB/9sAhAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB
AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/xAAfAAABBQEBAQEB
AQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYT
UWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNU
VVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3
uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEB
AQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFR
B2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpT
VFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1
tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/
AP66v+Cnn7OnxZ/aS/ZU8QeH/gV45+IHg74s/D/xFoPxZ8G6P4A+JfjT4Ty/FS48EG7n1X4O
eIPF3gHWvD/iLTtH+I+gXWq+HrK/ttSiTQvFE/h7xHIkq6P5M35T/Ab9m/8AZ4/aF+FPgz4v
eBPjB+2zFoXjDTPtdxot/wDtwftdWes+F/EdjN/Zfi3wN4gtf+FyQNo3iXwfrVhfaL4gspwJ
dI1jTLlSjSxBpPyzxo8UPEDw14Y4czHgmvk2EwjzjH4DPHmPCeQZ/OrWxWFpYrJ+WvmuXYqr
RvTwOb0eT2lOlF+wlCM5c6qfacEcPZFxDjMfhc3pV6lWnhqdfCexzDFYJKEZOniE40J04z5e
ajJNqUl73wrV+w6j+wh4Au9G1HQbD4v/ALZWiXGuaabey8QWX7an7U11qGkXh05YrLVLCK++
LdxYi40qYwXK2l/bXllcy20dxqUF3Axhl+9P+Cen7S3ir4t+C/GPwP8AjbdJ/wANO/sv6npH
gD4szsi2o+I/h+/037Z8Mvj3odrtiJ8P/Fvw1AdQuzDEtvpfjfTPGPhwLE2j+U3jeCnjjxV4
uR4nyXjalkf9s8P0cuzjJq+TcO5Nw/7TJksLlOcU68clw2Hp43/asZw/icNUxPPiIOWZNyf7
xu+NOCct4V/s/G5LLFfUcZKthcXDGY3FY6cMXaLwSpSxM5+yj7LDY2NdKX7yfsJe7qqn6I0V
+2HxB+O37fPxb8X/ABr+Nfw//wCCfvwU8W+JvCC/Z/D3xu/bI+JvgPX9S8M+Ivh78ENM1pZ/
Bfwi0DxVoGoafrXh3x/+0L4i0qbT5bjS7q21jQfhXonizWIHtZ9Z0K7k56+/Y++EMunw2b69
+0alvYKzxRwftj/teW7l1iYbpZ0+N/mzmfLEvKXTeqeWkLDZJ/O/i5418XcAZ0+G+Ea2VUYV
cmwtbNamNybLszr08TjXUr0aWHq4/DVngn/ZssLVU8M6VSpHF6VG4Uz9G4S4NyrO8DTx+aQr
zaxs1hVSxNfDw9nCPsJSnGhOCqx5/b+7V5qcZUlJwTjB1PkH9q74PeFvhd4L8O/D74N6n+0L
4j/aM+Pnii2+EX7PPhO5/bG/bFu4JPHOtWt3eX3i3xHt+N/m23gX4W+HV1n4gePNU8wQW/hz
RHs/Ka41jTrS4/fv9m74QXfwA+Avwk+C+oeP/GnxV1P4beBPD/hTVviT8RNd1DxJ418c6xpt
jGmr+J/EGs6pcXV9c3msakbq8WKa4lWxt5YdPgYW9rCJP0Xwp4z46444HwWdcbYrKsQqmPxm
H4ejl2RZPk8v7GwCp4OeJxNXK8vwVTH1MTm0Mzw7rY2piqsf7OjGFSC54VPB4uyvJcnzZ4LJ
qGIoqNCnVxjr4mtXbxNf94qcY1qlT2cadD2Moxp8kV7TlcZuPM/zv/4K9za7qHhX9iz4eab4
3+JHgbQPix+2/wCBfA3jq4+FnxC8W/DDxNrnhNfg/wDG7xU+gHxZ4F1bQfE9rp1xrXhjRry5
g0zVbRp3sYBMzQJIsvziP2CfhB+9jh+Lf7aMRRzKjL+3J+14wcxO3lt/yWTKoIpcnEe5IxmN
mcIlfB+Nvjlx34WZpw3kvCVfJMJhMzyKpjsRLMOFcgzutLGVc2zTDSq/Wc3wOKq04U8Nl2Hp
whCSowvUcIqrUqOp9BwRwbknEeBx2MzOjiKtTD472EPY5hisJH2cMNhqkY8tCpCPx1Zt6e8o
qMmo6u3a/sF/DCHiH4qftl3EmVXbN+3D+1vtHkzWUqwqH+MrlTEcedNi3JhWKEMYoDFJe/4Y
c+GGoSi+l+Jf7X6m7t7mCWKP9tz9rG1jaONvLjaKFfjFshkm3/ZIZUT7RHFuW1kWFk2/jNL6
YnjhB06P1ngypTTnNVn4bcEJVnKeDhyT/wCEjnUWoQqUaUXCMVKcZJVPaPEfWVfCXgyTdTkz
anJc0HShn2a8qbjzbQxGyVGzcY8urcVf3qkNz+wn8ImtYmPxX/bGeSKAeWi/tv8A7XNq8gE0
iPLJJB8Zoy91HubbK8ruD5k6sXlaSus8Df8ABOb4JalqeJfil+2hIsRKG2b9uz9rtyCCYWf5
PjW0n7qQqym3BYNLD0dd5+r4W+lf4t5vxTkmFxON4RqQlNU6lOn4e8F0qdalVWJlicNKhTyi
LrVYuShCulzxjGKpVKdWFGqebmnhnwzl+VYypSw+ZxkoVOVzzrMakoPnXsqsasq0nCCUrO7s
pcil7vNGe74i/wCCcPwV8L6nNc6T8UP2y4gbr7HFBP8At1/tf3kUSpbrOJljufjQyrOfMlG9
4vMCNthdLZo8/Ptp8F9E/Zf/AGx/+CfmofDj4nftP3Z+LX7Q3jn4deMdF+IX7VP7QnxY8J63
4al/Zn+PPjRbTVfCnxK+JXirw0/2TxH4Z0i9tLk6Z58dxbWUdpdqYreGT9GyPxr49zPxUwXB
2a1+H63DtbE59QdClwvkODxKjXyrNJ0IyxmDwFDGVPqlerF4WVSU6kJU8PUheVKCPlsdwdlF
LhfE5xg/rlLMfY4L3p47EVKSjRxFD2ko0KkpUYudNy5nTUOe7TfIos/oxr8Af2w/BMvx1/4K
ba78JvGXxK+PPh74d+DP2HvhX470Dwx8J/jz8YfgzpK+L/FPxp+Nmh6zrOoQ/Cvxn4TTWL6+
0/wz4fsjLq63j20Wn2q2pgDSmX9N444ozPgrgjivifJJYWnm2U5Zh54CrjMDgsxoUZ4nOcrw
NabweYUa+Eqv6picRGPtKNR0nL2tJRq04TPnuHcsw2cZ5lmW4tTlhsTWqxqwp1J0XJU8Hiak
V7Sk4Tj79OD0lHaz092rTX9gf4SSbfs/xd/bSQLth2r+3F+11lV80Pv2r8aS2Fdg8JjcBmKx
lYj5Dy6Fr+w38NdLQXUHxO/bEmEKSZM/7bn7WlxgXUdmu/yj8Yzy/wC7NpCsz/Y1wsCxNBvu
P48X0w/G6EJ4mhjOEKynRqNYeXhtwQ/ZRqYeUJOPNlEYuSi3KjdSjTnRk5OOIcZR/YanhPwb
VXsJUcyoptwVSnnuZp3l/hrxvaMvKPwqCvH3pf8AhhD4VRrMH+KH7YcaLdR3AK/tv/tZP5Lu
gaWMxj4xgSWcHm+Q1om2yJuJm+zs5EbTj9hj4PW2pw3b/Ev9r3UAk1xJcWc37cH7Xa2n7lWk
ED2yfGm3iktBkzNGMebIjS/NNsSu2r9MHxkqYWvSxGP4PpxqL2L9j4d8E0q8oTxC56tLEf2L
+5q0/ZxSkuSLUnS5eWTMKfhRwlCcalKjmslGLd6ueZrOkpKNOcI1KU8RaUH3ivh+1d2qezeA
P+CffwpuNP1/+zfi/wDtoaQ2twXebnSP24/2rw1hKou3thp8d58XdQgsXgWeAwzTwTbt0KuN
ny1z7/s6/tD/AA0Wxi+EX/BQr9q/T7q2iTUJE+M0/wAMP2hdI1TzxC8Vjqtr498BRa+mnwiF
kI0HxT4evpVnnP8AaAbyjB+r4r6Q3G2G4Q4dz3Ncq4P4gxGNwtTCYv2nD2GyOU6fsYSp4nCV
uHXlMIY6ioxhHEVoY2E+S1ejVlzQl8iuBsnxGb5jgcPXzLAQoTp1aapYn23LySlehVhjKdeT
pz5bVIwlTnyWUakI2Zrab/wUH+NH7MPiTSPD/wC354M8Gy/B3W7+HR9N/bR+COm61pHwz8K6
ldPIunQftAfCvX9a8U+JvhHpl83kWSfEHR/FHjXwBbXzqfEl54RtJklX9ibO8s9Rs7TUNPur
a+sL62gvLG9s5ormzvLO5iWa2urS5gZ4bi2uIXSWCaF3ilidXjZkZWb9p4Z4myXjHI8Dn+Qz
r/VcTD2OLwmKUPrWVZpQjFY3La8qdqdb2UnGrhsVThThi8FWw9f2VCq6uHj8XmeVYzJsZWwO
NUHOE5ujVp8yp4jDOT9hXipJOLlCyqQ2hVU4xbhyyqWa/mY/aP8A2Zh8Pv8AgoZ4k8P/ABs+
M/7V83wm/bMu9R8e/s0+JvDX7WX7R3gHw54C+LfhrSIZfiT+zYdD8FfEjQfDOnQ6xplsfiX8
KBDZW015pcXjLwxDvfwrpS3W/E2fcScN8HcXZpwg8FDiHB5FWxuAqY3JstzynCnl1ehmGZRh
gszw+Joc9XKcNj6cJQozqqbhyRv7zvJMHl2OznK8JmsaksDXxUaFVUsTVwkuarCdLD/vqMqc
lD6y6PNHmjGS0bsv3nstr+wZ8L4ubf4qftk3R8uKQeZ+3H+1vtCpcWrCJQ/xkfb5UijzJv8A
Rne28pflghWOfCvLzVf+Cd/xB8FftOeH/HXx28Z/s66hfRfDz9qjwR8S/jH8UfjHZ+EPA+v6
rp9n4f8A2gfCln8SfFXi3UvD9x8LNcktV8cWHh6aGz1H4c6rrWqzWU0+gWVxD/Nvhf8ASh8R
+KuOuHODONJcLYvhzibFVskqYnBcE8L5Ni6WZ5vChl2TYmGPyzA4fH4SlhM6nluJnGFSNCeB
eLozhJ1Ks6v6LxP4Z5Dl+T4/NcmWPo5jl9JYlUa2a4/F4d0KUlXxcHh6tR0ZyeBwuJjTtFct
a0lqpOp/QxbXNteW1vd2c8F1aXUMVxa3VtLHPbXFvMgkhnt5omaKaGWMq8UkbMjoQysQfnnr
+qLW0as1o1a1rdLdLdun5/kys0mrNNKzWzXS3S1tv65vPvit8UfAnwR+Gvjn4u/E7xBZeFPh
98N/C+seMPF/iHUHEdrpehaHZyXt7ORwZpjHD5VpaRBri8u5ILS2je4ljjm/Bf4W/Bnx9+13
c+Iv2tf2nfGv7R/gDxH8Z9VTXPhV8CvAX7RHxq+EGgfAf4HR2UVj8O/BWteF/hp438M6FffE
/VdJE3jD4ja/qFjc3tt4w8QXegWs0FpoNv8AafzfxO8R808MckwOcZFSy2rnOOzF4PA081wF
DMsJ7CjQdXMKzwWIjKjW9jGphKMualP2LxtKpZNLn+l4Y4dw3EeKxGFxvt1gqWGbrSw1aeHq
qpUfLh4xq0+WVPm5Ks+aM4PlpSS3udjP/wAE+fg+11PMnxV/bKikYvNJI37d/wC2KI9twFSU
/Zx8a/LjjRrckKvlrETNC9usE8stxzX/AATd+BN945/bP+Jn7Rfw2+LH7Rb/ALLn7P8AY+MP
gJ4a0rx1+0p8dfi14U/aA+Ot9eRL8TfFsWkfEnx94m0F/AvwShRvAXh+806wCa98RL3xTfpc
p/whtl9o+Q8F/GXxS8Qsx4lyrPK/DcuF8JhHmeZSwvCeQ4XMp5tjcVDD5dgcNm9DAQxuW4aU
f7QxscJg8RSoShlkqKoRpz5j6DjDhXhvIMvwdbB08b/aVaosPQdTG1pUvq8Ie0rVZUJz5Ksl
H2NPmlDnTqwm5af7R/Q7RX7ufnYV+IPx38F2n7EH7VUXxNsI57H9l/8AbU+IGn6V44trcpZa
B8F/2rtVsxbab4tzBsGm+G/2kLfTLfQdYkdFs7b4vW+l6hcTC48buK+Z454cocXcA8b8N1Ka
nXxnDmLzDK2rqrHN+G50eJMDRw1l/vGa/wBkVeH4bLkzepfTSfscPZjPKc9ynGRfLBY2lhcR
/J9Wx18DUnNbSjh/bxxdpe5zYeN3BLmf0iiN5aOGFw1vbq5kC+bEsey3AVY95VfKZbkCN1+U
BpFXgE/LH7Q2r+Pf2frrw5+2V8G/Ctx4s8afCjT7e3+LfgHSIUfWvi7+znb30V5488LaRCst
u1/418IadLfePPh9byySed4i0640URBPEU2z/PTwL4tpcEeJXDmb4ufNlOLlVyLOal4+yllf
EOFWQVcTzVGof8JrxeHzWhFez562X0KnKon7vx/kMOJeGMZl0ZSo16VfCZphPZtqVOtk+Lw+
dUacUoaRxUsG8DU/d39niaierjz/ALP/AA3+Ifgz4ufD/wAF/FH4d69Y+J/AnxB8MaJ4w8Ie
IdNkEllrHh7xBp8Gp6VfQN1UT2lxEzxOFlgk3QzIksbpXjf7XX7S/hn9kr4E+K/jBr2nXPiT
V7aXS/Cvw3+H+lug8QfFL4seML2PQfhz8NPDUTEebrHi7xLdWdgr/wCq07T/ALfrN4YtP028
nX/T6hgas8wp5bW/2Ss8XHB1/b/u1hZKr7Ks69/gWHtJ1br3FCV9v3n82837vngub3OaCWvN
7t4pW76dfu+3+d/7KXwN8TfCLwb4l8TfFXVLTxR+0V8cPFWpfF79obxpbDfBq3xI8Rww27+G
dEIWF4/A/wAMtGs9K8A+AdPUr9g8M6HbEKt7f38979F65rVl4e0DWPEWt3lnpWjaLpN3quqX
1/cpaWGl6XpttPdajqV7dy+QlvYwafC11O7+UkMcEhJhkUmv8w/ELP6/FvG/FOe4eE3HOc4x
tTAULXq08uhN4LJcAlCUk/YZfSwuEpx5qkpKlTfv2/e/0zkuCoZblOXYSTjFYbDUIVZe6qft
OTnxNa1rNe1U60rpR5J+9tBVPEP+Cc/w41T4++P/ABR/wUf+JWkXtjZ+O9BvPhv+xj4R1u0e
2ufA37NX9pLeaj8UpbC4/eWPjD9pPWrK08Wz3EkMN7a/DXTPAulh/Lu9QS4/Y2v9GuH8njw3
w7w/w3Dl5cgyfB5ZL2f8OWKpxdbMq0OnLic0rY3FK2j9tf8A6+fzxmuM/tHMsfj9bYvFVasO
a/N7K/JQUr63jQhShrty2Vkkn+Rn/BV0A6l/wToGSv8AxsD8JfdYx42/s6ftIsPmXGB8vPVS
uVZSpw/pNsYo9uxZhKP9c8DxOSnnyBQiMSmftHkDj7yDp5fzXH8cfSwVOPFnA7k53fBtT2cY
1LWk+Jc9hzcns3F7WipyUed8yakkfr/hXf8AsnNkuVJ5pFvmjdOKwWGunJW5V7q3urcy+2+f
lfGXj7wB8OdP0vVPHvjnwn4Bsb1JYre68X+KdH8O2+oNaJYtcpYT65fWcMk1tCftHlwuzwwx
LNtThl870f8AaW/Zw1S9/s/S/wBoL4G3k0NsfPGn/FbwHdywCOSMSyTJH4hl4ivESNiwKO7t
GG2iLb+CZR4d8ecQ08DjOHuCeMc6wOYVJ4fA4nKOHc6zelWq0KNB4+nh8RhMJUoV6lCdL2uI
5HKeCgl7apFXU/ucZxDkOWQxP9p51k+A+qU/a4j63mODwKp0/af7O68a9Wn7KjN1IxhKdozX
vuPMrTrN+1R+zBJam2T9ov4CPNCYVnth8Zfh2Z7aWN597Nb/APCR+YDPDu3LIqFVKYaWIZXv
Ph1+1v8Asr2WstJP+01+zzaW0xtz50nxd+HFlC9u5lMfk3h8Sp5KOfssuTmQM6j/AFm+Wf7H
g3w48RcDxZkGMxHAHGGEo0Z0a2IxtXhbO3Tp4elPE4bFVJ1lgIUcLSo14OlUqVp0owr0owqQ
vGx5ec55klbKcxo0s4yyrVnTqqNKnmGETnJyozp8sI1pSq897xai3KPNCL/n6D4gftffsqXW
pXEtr+1D+ztJax38oQj4zfDJhukSMR7Hg8SBESVodsuxtsknRDIxc/D3xH+NXwX+KH7Zn/BL
bSfht8Wfhh8QtS079rHxtq02meCPHfhPxlqdhp//AAyH+0jZvf3NpoWsajNBY+bcx25vnjEM
ckqeXcOZEik/eeDOC+MKXj5hMwx3C3EVHAUauf494nE5HmeHo0MF/YGc1KONr13hVRp0VCNK
X1lzjQjzRlTm/d5viMxzLLf9R6+HpY7BOqsNhaPsoYujKbqPE4fmjGHNz3k5JKHxtxba0kp/
0TV+H3xcA/4e3fE3GFI/4J9/ABd24Idj/H39pAOgPfcFHydXIGFYhUk/Y/GZL/iEXiJeThFZ
HgrtPltF8SZDF62e8W1ZLX4dpe/8TwYv+MqyPyxVTS19PqeKja3o/wDgdJfTYMRwsSTCLz8q
nmK0fmCdBKXkXdIo8poYkeM/Kc+XvDFpPM/G/wAYvg18OtUk0b4g/Fv4a+BLvy7O7Oj+M/H/
AIY8O6hFZyW3mJeNZaxrmn3TW0kVrcRQ3Cq8cqQXKxSs8Kxt/mxlOQ5txJUll/DmT5xnONhQ
nWWCyvC43M8S8BQoYhYp/V8DQliPZ0YpVMTi5Rp+whGTqTlGx/R+Kx2Fy9e2x2KwmGovR1a8
6eHh7ao4+yvOt7sJy96nSp63vG3LJ80uat/2lv2dLrS73VIv2gPgjJp9jcBZry2+Knw/axDs
